name: jaguar_http
description: An Http Api generator inspired by Retrofit for Dart.
version: 0.0.1
authors:
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_serializer: "^0.5.1"
  http: "^0.11.3"

dev_dependencies:
  test: ^0.12.0
